#!/usr/bin/env python3
"""Generate tests/syntax_test_conformance.pzl from the expression conformance table.

Usage:
    python3 tests/generate_conformance_test.py <expressions-parse.json>

The table lives in the Puzzle monorepo at
packages/puzzle-lang/conformance/expressions-parse.json. Every case the
compiler parses successfully ("ok": true) is written into five positions —
a text interpolation, a brace-only attribute value, a quoted attribute value,
an {#if} header and an @event handler — and asserted to carry no `invalid`
scope and to close on the right brace. A case parsed in argument context
(an arrow function at the top level) is wrapped in a call first.

The rule tests for the invalid side (`|`, `this`, markup-function placement)
are hand-written in tests/syntax_test_puzzle.pzl.
"""

import json
import os
import sys

HEADER = """## SYNTAX TEST "Puzzle.sublime-syntax"
## Generated by tests/generate_conformance_test.py from the Puzzle expression
## conformance table (packages/puzzle-lang/conformance/expressions-parse.json).
## Do not edit by hand: every expression the compiler accepts must highlight
## without an `invalid` scope, in every template position.

<puzzle-view>
"""

FOOTER = "</puzzle-view>\n"
INDENT = "    "


def caret(col, width, selector):
    if col < 2:
        raise ValueError(f"assertion column {col} is inside the comment token")
    return "##" + " " * (col - 2) + "^" * width + " " + selector


def emit(out, prefix, src, suffix, close_selector):
    """Write one position. `prefix` + src + `suffix` is the template text; the
    first `}` of `suffix` is the brace that must close the expression."""
    lines = (prefix + src + suffix).split("\n")
    # Assertions only follow a line once the construct has closed, so a
    # multi-line case is asserted on its last line.
    if len(lines) == 1:
        start = len(prefix)
    else:
        start = len(INDENT)
    last = lines[-1]
    close = len(last) - len(suffix) + suffix.index("}")
    out.extend(lines)
    if close > start:
        out.append(caret(start, close - start, "- invalid"))
    if len(lines) == 1:
        out.append(caret(start, 1, "source.js.embedded.puzzle"))
    out.append(caret(close, 1, close_selector))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8") as fh:
        table = json.load(fh)

    out = []
    count = 0
    for case in table["cases"]:
        if not case["ok"]:
            continue
        count += 1
        src = case["src"].replace("\r\n", "\n")
        # Continuation lines are indented so their assertions have room; the
        # extra spaces are white space or string text in every case.
        src = src.replace("\n", "\n" + INDENT)
        if case.get("argument"):
            src = "f(" + src + ")"
        end = "punctuation.section.embedded.end.puzzle"
        # The name is template text: keep braces and tags out of it.
        name = "".join(c for c in case["name"] if c not in "{}<>\\")
        out.append(f"{INDENT}## {name}")
        emit(out, INDENT + "<p>{ ", src, " }</p>", end)
        emit(out, INDENT + "<p title={ ", src, " }>x</p>", end)
        if '"' not in src:
            emit(out, INDENT + '<p title="{ ', src, ' }">x</p>', end)
        elif "'" not in src:
            emit(out, INDENT + "<p title='{ ", src, " }'>x</p>", end)
        emit(out, INDENT + "{#if ", src, "}x{/if}", end)
        emit(out, INDENT + "<b @click={ ", src, " }>x</b>", end)
        out.append("")

    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "syntax_test_conformance.pzl")
    with open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER + "\n".join(out) + "\n" + FOOTER)
    print(f"{count} valid cases -> {os.path.relpath(target)}")


if __name__ == "__main__":
    main()
